---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5.0-jdk-8

inputs:
  - name: project-brian

outputs:
  - name: build

run:
  path: project-brian/ci/scripts/build.sh
