---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: project-brian

outputs:
  - name: build

run:
  path: project-brian/ci/scripts/build.sh
